<?php
if (!defined("allow entry"))
	require('hackingattempt.php');

function nameCheck() {
	require_once('databasemanager.php');
	$con = makeDatabaseConnection();
	$ps = $con->prepare("SELECT COUNT(*) FROM `accounts` WHERE `name` = ?");
	$ps->bind_param('s', $_GET["name"]);
	$ps->execute();
	$ps->bind_result($usermatchcount);
	if ($ps->fetch() && $usermatchcount > 0)
		echo $_GET["name"];
	$ps->close();
	$con->close();
}

function registerForm() {
	echo "<?xml version=\"1.0\" encoding=\"us-ascii\"?>\r\n"
		. "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\r\n"
		. "  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n"
		. "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\r\n"
		. "<head>\r\n"
		. "<title>Project Throwback Registration</title>\r\n"
		. "<meta http-equiv=\"Content-Type\" content=\"text/html;charset=us-ascii\" />\r\n"
		. "<link rel=\"stylesheet\" type=\"text/css\" href=\"common.css\" />\r\n"
		. "<style type=\"text/css\">\r\n"
		. "body {\r\n"
		. "	font-family:\"Lucida Grande\", \"Lucida Sans Unicode\", Verdana, Arial, Helvetica, sans-serif;\r\n"
		. "	font-size: 12px;\r\n"
		. "}\r\n"
		. "p, h1, form {\r\n"
		. "	border: 0;\r\n"
		. "	margin: 0;\r\n"
		. "	padding: 0;\r\n"
		. "}\r\n"
		. ".spacer {\r\n"
		. "	clear: both;\r\n"
		. "	height: 1px;\r\n"
		. "}\r\n"
		. "/* ----------- Reg Form ----------- */\r\n"
		. ".regform {\r\n"
		. "	margin: 0 auto;\r\n"
		. "	width: 400px;\r\n"
		. "	padding: 14px;\r\n"
		. "}\r\n"
		. "\r\n"
		. "/* ----------- stylized ----------- */\r\n"
		. "#stylized {\r\n"
		. "	border: solid 2px #b7ddf2;\r\n"
		. "	background: #ebf4fb;\r\n"
		. "	filter: alpha(opacity=80);\r\n"
		. "	opacity: 0.8;\r\n"
		. "}\r\n"
		. "#stylized h1 {\r\n"
		. "	font-size: 14px;\r\n"
		. "	font-weight: bold;\r\n"
		. "	margin-bottom: 8px;\r\n"
		. "}\r\n"
		. "#stylized p {\r\n"
		. "	font-size: 11px;\r\n"
		. "	color: #666666;\r\n"
		. "	margin-bottom: 20px;\r\n"
		. "	border-bottom: solid 1px #b7ddf2;\r\n"
		. "	padding-bottom: 10px;\r\n"
		. "}\r\n"
		. "#stylized .small {\r\n"
		. "	color: #666666;\r\n"
		. "	display: block;\r\n"
		. "	font-size: 11px;\r\n"
		. "	font-weight: normal;\r\n"
		. "	text-align: right;\r\n"
		. "	width: 140px;\r\n"
		. "}\r\n"
		. "#stylized .row {\r\n"
		. "	padding: 2px 0 20px 0;\r\n"
		. "}\r\n"
		. "#stylized .row .label {\r\n"
		. "	display: block;\r\n"
		. "	font-weight: bold;\r\n"
		. "	text-align: right;\r\n"
		. "	width: 140px;\r\n"
		. "	float: left;\r\n"
		. "}\r\n"
		. "#stylized input {\r\n"
		. "	font-size: 12px;\r\n"
		. "	padding: 4px 2px;\r\n"
		. "	border: solid 1px #aacfe4;\r\n"
		. "	width: 194px;\r\n"
		. "	margin: 2px 0 0 10px;\r\n"
		. "}\r\n"
		. "#stylized .birthdate {\r\n"
		. "	float: left;\r\n"
		. "	width: 200px;\r\n"
		. "	margin: 2px 0 0 10px;\r\n"
		. "}\r\n"
		. "#stylized .birthdate input {\r\n"
		. "	float: right;\r\n"
		. "	width: 50px;\r\n"
		. "	margin: 0 0 20px 0;\r\n"
		. "	padding: 4px 0;\r\n"
		. "}\r\n"
		. "#stylized input#register {\r\n"
		. "	clear: both;\r\n"
		. "	margin: 0 0 0 150px;\r\n"
		. "	padding: 0;\r\n"
		. "	width: 125px;\r\n"
		. "	height: 31px;\r\n"
		. "	background: #666666;\r\n"
		. "	text-align: center;\r\n"
		. "	line-height: 31px;\r\n"
		. "	color: #FFFFFF;\r\n"
		. "	font-size: 11px;\r\n"
		. "	font-weight: bold;\r\n"
		. "	border: none;\r\n"
		. "}\r\n"
		. "\r\n"
		. "/* -------- popup hint box -------- */\r\n"
		. ".hintbox {\r\n"
		. "	position: absolute;\r\n"
		. "	top: 0;\r\n"
		. "	background-color: #ebf4fb;\r\n"
		. "	filter: alpha(opacity=80);\r\n"
		. "	opacity: 0.8;\r\n"
		. "	width: 150px; /*Default width of hint.*/\r\n"
		. "	padding: 3px;\r\n"
		. "	border:1px solid black;\r\n"
		. "	font:normal 11px Verdana;\r\n"
		. "	line-height:18px;\r\n"
		. "	z-index:100;\r\n"
		. "	border-right: 3px solid black;\r\n"
		. "	border-bottom: 3px solid black;\r\n"
		. "	visibility: hidden;\r\n"
		. "}\r\n"
		. "</style>\r\n"
		. "<script type=\"text/javascript\" src=\"common.js\"></script>\r\n"
		. "<script type=\"text/javascript\">\r\n"
		. "// <![CDATA[\r\n"
		. "var horizontal_offset = -8; //horizontal offset of hint box from text field, in pixels\r\n"
		. "\r\n"
		. "var vertical_offset = -8; //horizontal offset of hint box from text field, in pixels\r\n"
		. "var ie = document.all;\r\n"
		. "var ns6 = document.getElementById && !document.all;\r\n"
		. "var nextZ = 0;\r\n"
		. "\r\n"
		. "function getPosOffset(what, offsettype) {\r\n"
		. "	var totaloffset = (offsettype == \"left\") ? what.offsetLeft : what.offsetTop;\r\n"
		. "	var parentEl = what.offsetParent;\r\n"
		. "	while (parentEl != null){\r\n"
		. "		totaloffset = (offsettype == \"left\") ? totaloffset + parentEl.offsetLeft : totaloffset + parentEl.offsetTop;\r\n"
		. "		parentEl = parentEl.offsetParent;\r\n"
		. "	}\r\n"
		. "	return totaloffset;\r\n"
		. "}\r\n"
		. "\r\n"
		. "function ieCompatTest() {\r\n"
		. "	return (document.compatMode && document.compatMode!=\"BackCompat\") ? document.documentElement : document.body;\r\n"
		. "}\r\n"
		. "\r\n"
		. "function clearBrowserEdge(dropmenuobj, obj, side) {\r\n"
		. "	var edgeoffset = (side == \"right\") ? horizontal_offset * -1 : vertical_offset * -1;\r\n"
		. "	if (side == \"right\") {\r\n"
		. "		var windowedge = ie && !window.opera ? ieCompatTest().scrollLeft + ieCompatTest().clientWidth + 10 : window.pageXOffset + window.innerWidth;\r\n"
		. "		if (windowedge - dropmenuobj.x < dropmenuobj.offsetWidth + horizontal_offset)\r\n"
		. "			edgeoffset = dropmenuobj.offsetWidth + obj.offsetWidth + horizontal_offset;\r\n"
		. "	} else {\r\n"
		. "		var windowedge = ie && !window.opera ? ieCompatTest().scrollTop + ieCompatTest().clientHeight - 15 : window.pageYOffset + window.innerHeight - 18;\r\n"
		. "		dropmenuobj.contentmeasure = dropmenuobj.offsetHeight;\r\n"
		. "		if (windowedge - dropmenuobj.y < dropmenuobj.contentmeasure)\r\n"
		. "			edgeoffset = dropmenuobj.contentmeasure - obj.offsetHeight;\r\n"
		. "	}\r\n"
		. "	return edgeoffset;\r\n"
		. "}\r\n"
		. "\r\n"
		. "function showHint(menucontents, obj, tipwidth, error) {\r\n"
		. "	if (ie || ns6) {\r\n"
		. "		var dropmenuobj = getHintBox(obj);\r\n"
		. "		dropmenuobj.innerHTML = menucontents;\r\n"
		. "		if (tipwidth != \"\") {\r\n"
		. "			dropmenuobj.widthobj = dropmenuobj.style;\r\n"
		. "			dropmenuobj.widthobj.width = tipwidth;\r\n"
		. "		}\r\n"
		. "		dropmenuobj.x = getPosOffset(obj, \"left\") + obj.offsetWidth;\r\n"
		. "		dropmenuobj.y = getPosOffset(obj, \"top\");\r\n"
		. "		dropmenuobj.style.left = dropmenuobj.x - clearBrowserEdge(dropmenuobj, obj, \"right\") + \"px\";\r\n"
		. "		dropmenuobj.style.top = dropmenuobj.y - clearBrowserEdge(dropmenuobj, obj, \"bottom\") + \"px\";\r\n"
		. "		dropmenuobj.style.visibility = \"visible\";\r\n"
		. "		dropmenuobj.style.zIndex = nextZ++;\r\n"
		. "		if (error)\r\n"
		. "			dropmenuobj.style.backgroundColor = \"#CC3300\";\r\n"
		. "		else\r\n"
		. "			dropmenuobj.style.backgroundColor = \"#FFCC66\";\r\n"
		. "	}\r\n"
		. "}\r\n"
		. "\r\n"
		. "function hideHint(obj) {\r\n"
		. "	var dropmenuobj = document.getElementById(\"hintbox_\" + obj.getAttribute(\"id\"));\r\n"
		. "	if (dropmenuobj != null) {\r\n"
		. "		dropmenuobj.style.visibility = \"hidden\";\r\n"
		. "		dropmenuobj.style.left = \"-500px\";\r\n"
		. "	}\r\n"
		. "}\r\n"
		. "\r\n"
		. "function hintVisible(obj) {\r\n"
		. "	var dropmenuobj = document.getElementById(\"hintbox_\" + obj.getAttribute(\"id\"));\r\n"
		. "	if (dropmenuobj != null)\r\n"
		. "		return (dropmenuobj.style.visibility == \"visible\");\r\n"
		. "	return false;\r\n"
		. "}\r\n"
		. "\r\n"
		. "function createHintBox(id) {\r\n"
		. "	var divblock = document.createElement(\"div\");\r\n"
		. "	divblock.setAttribute(\"id\", \"hintbox_\" + id);\r\n"
		. "	divblock.setAttribute(\"class\", \"hintbox\");\r\n"
		. "	document.body.appendChild(divblock);\r\n"
		. "	return divblock;\r\n"
		. "}\r\n"
		. "\r\n"
		. "function getHintBox(obj) {\r\n"
		. "	var dropmenuobj = document.getElementById(\"hintbox_\" + obj.getAttribute(\"id\"));\r\n"
		. "	if (document.getElementById(\"hintbox_\" + obj.getAttribute(\"id\")))\r\n"
		. "		return dropmenuobj;\r\n"
		. "	dropmenuobj = createHintBox(obj.getAttribute(\"id\"));\r\n"
		. "	return dropmenuobj;\r\n"
		. "}\r\n"
		. "\r\n"
		. "var usernameOk = false;\r\n"
		. "var passwordOk = false;\r\n"
		. "\r\n"
		. "function hintTextMatch(obj, menucontents) {\r\n"
		. "	if (!hintVisible(obj))\r\n"
		. "		return false;\r\n"
		. "	return (getHintBox(obj).innerHTML == menucontents);\r\n"
		. "}\r\n"
		. "\r\n"
		. "function checkUsername(obj) {\r\n"
		. "	var xmlhttp;\r\n"
		. "	if (window.XMLHttpRequest) {\r\n"
		. "		//code for IE7+, Firefox, Chrome, Opera, Safari\r\n"
		. "  		xmlhttp = new XMLHttpRequest();\r\n"
		. "	} else {\r\n"
		. "		//code for IE6, IE5\r\n"
		. "		xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n"
		. "	}\r\n"
		. "	xmlhttp.onreadystatechange = function() {\r\n"
		. "		if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\r\n"
		. "			var resp = xmlhttp.responseText;\r\n"
		. "			if (resp != \"\") { //we'll return an empty string for no conflicts\r\n"
		. "				showHint(\"The username \" + resp + \" is already being used.\", obj, \"250px\", true);\r\n"
		. "				usernameOk = false;\r\n"
		. "				updateSubmitButton();\r\n"
		. "			}\r\n"
		. "		}\r\n"
		. "	}\r\n"
		. "	xmlhttp.open(\"GET\", \"index.php?action=namecheck&name=\" + obj.value, true);\r\n"
		. "	xmlhttp.send();\r\n"
		. "}\r\n"
		. "\r\n"
		. "function showUsernameHint(obj) {\r\n"
		. "	if (!hintVisible(obj) && obj.value.length == 0) {\r\n"
		. "		var message = \"Must be between 4-12 characters long. Permitted characters: uppercase and lowercase letters, numbers, and underscore\";\r\n"
		. "		showHint(message, obj, \"250px\", false);\r\n"
		. "		obj.onblur = function(obj2, event) {\r\n"
		. "			if (hintTextMatch(obj, message))\r\n"
		. "				hideHint(obj);\r\n"
		. "			obj.onblur = null;\r\n"
		. "		};\r\n"
		. "	} else {\r\n"
		. "		getHintBox(obj).style.zIndex = nextZ++;\r\n"
		. "	}\r\n"
		. "}\r\n"
		. "\r\n"
		. "function changingUsername(obj, event) {\r\n"
		. "	var code = event.charCode;\r\n"
		. "	if (code != 0)\r\n"
		. "		hideHint(obj);\r\n"
		. "	if (!(code >= 48 && code <= 57 || code >= 65 && code <= 90 || code >= 97 && code <= 122 || code == 95 || code == 13 || code == 0)) {\r\n"
		. "		showHint(\"Permitted characters: uppercase and lowercase letters, numbers, and underscore\", obj, \"250px\", false);\r\n"
		. "		event.returnValue = false;\r\n"
		. "		event.preventDefault();\r\n"
		. "	}\r\n"
		. "}\r\n"
		. "\r\n"
		. "function usernameChanged(obj, event) {\r\n"
		. "	var code = event.keyCode;\r\n"
		. "	if (code == 8 || code == 46)\r\n"
		. "		hideHint(obj); //backspace and delete will not fire onkeypress/changingUsername in webkit, so we have to remove hintbox here\r\n"
		. "	if (!hintVisible(obj)) {\r\n"
		. "		var length = obj.value.length;\r\n"
		. "		if (length < 4) {\r\n"
		. "			usernameOk = false;\r\n"
		. "			showHint(\"Must be at least 4 characters long\", obj, \"250px\", true);\r\n"
		. "		} else if (length > 12) {\r\n"
		. "			usernameOk = false;\r\n"
		. "			showHint(\"Must be less than 13 characters long\", obj, \"250px\", true);\r\n"
		. "		} else {\r\n"
		. "			checkUsername(obj);\r\n"
		. "			usernameOk = true;\r\n"
		. "		}\r\n"
		. "		updateSubmitButton();\r\n"
		. "	}\r\n"
		. "}\r\n"
		. "\r\n"
		. "function showPasswordHint(obj) {\r\n"
		. "	if (!hintVisible(obj) && obj.value.length == 0) {\r\n"
		. "		var message = \"Must be between 5-12 characters long. Permitted characters: uppercase and lowercase letters, numbers, and underscore\";\r\n"
		. "		showHint(message, obj, \"250px\", false);\r\n"
		. "		obj.onblur = function(obj2, event) {\r\n"
		. "			if (hintTextMatch(obj, message))\r\n"
		. "				hideHint(obj);\r\n"
		. "			obj.onblur = null;\r\n"
		. "		};\r\n"
		. "	} else {\r\n"
		. "		getHintBox(obj).style.zIndex = nextZ++;\r\n"
		. "	}\r\n"
		. "}\r\n"
		. "\r\n"
		. "function changingPassword(obj, event) {\r\n"
		. "	var code = event.charCode;\r\n"
		. "	if (code != 0)\r\n"
		. "		hideHint(obj);\r\n"
		. "	if (!(code >= 48 && code <= 57 || code >= 65 && code <= 90 || code >= 97 && code <= 122 || code == 95 || code == 13 || code == 0)) {\r\n"
		. "		showHint(\"Permitted characters: uppercase and lowercase letters, numbers, and underscore\", obj, \"250px\", false);\r\n"
		. "		event.returnValue = false;\r\n"
		. "		event.preventDefault();\r\n"
		. "	}\r\n"
		. "}\r\n"
		. "\r\n"
		. "function passwordChanged(obj, event) {\r\n"
		. "	var code = event.keyCode;\r\n"
		. "	if (code == 8 || code == 46)\r\n"
		. "		hideHint(obj); //backspace and delete will not fire onkeypress/changingPassword in webkit, so we have to remove hintbox here\r\n"
		. "	if (!hintVisible(obj)) {\r\n"
		. "		var length = obj.value.length;\r\n"
		. "		if (length < 5) {\r\n"
		. "			passwordOk = false;\r\n"
		. "			showHint(\"Must be at least 5 characters long\", obj, \"250px\", true);\r\n"
		. "		} else if (length > 12) {\r\n"
		. "			passwordOk = false;\r\n"
		. "			showHint(\"Must be less than 13 characters long\", obj, \"250px\", true);\r\n"
		. "		} else {\r\n"
		. "			passwordOk = true;\r\n"
		. "		}\r\n"
		. "		updateSubmitButton();\r\n"
		. "	}\r\n"
		. "}\r\n"
		. "\r\n"
		. "function updateSubmitButton() {\r\n"
		. "	document.getElementById(\"register\").disabled = (!usernameOk || !passwordOk);\r\n"
		. "}\r\n"
		. "\r\n"
		. "function updateValidBirthdays(obj) {\r\n"
		. "	var days = document.getElementById(\"birthdayselect\");\r\n"
		. "	//february will always be a leap year...\r\n"
		. "	switch (obj.selectedIndex) {\r\n"
		. "		case 0: //january\r\n"
		. "		case 2: //march\r\n"
		. "		case 4: //may\r\n"
		. "		case 6: //july\r\n"
		. "		case 7: //august\r\n"
		. "		case 9: //october\r\n"
		. "		case 11: //december\r\n"
		. "			switch (days.length) {\r\n"
		. "				case 29: //last was february\r\n"
		. "					var option = document.createElement(\"option\");\r\n"
		. "					option.text = \"30\";\r\n"
		. "					option.setAttribute(\"value\", \"30\");\r\n"
		. "					days.add(option, null);\r\n"
		. "					option = document.createElement(\"option\");\r\n"
		. "					option.text = \"31\";\r\n"
		. "					option.setAttribute(\"value\", \"31\");\r\n"
		. "					days.add(option, null);\r\n"
		. "					break;\r\n"
		. "				case 30: //last was either april, june, september, november\r\n"
		. "					var option = document.createElement(\"option\");\r\n"
		. "					option.text = \"31\";\r\n"
		. "					option.setAttribute(\"value\", \"31\");\r\n"
		. "					days.add(option, null);\r\n"
		. "					break;\r\n"
		. "				case 31: //last was either january, february, march, may, july, august, october, december\r\n"
		. "					break;\r\n"
		. "			}\r\n"
		. "			break;\r\n"
		. "		case 3: //april\r\n"
		. "		case 5: //june\r\n"
		. "		case 8: //september\r\n"
		. "		case 10: //november\r\n"
		. "			switch (days.length) {\r\n"
		. "				case 29: //last was february\r\n"
		. "					var option = document.createElement(\"option\");\r\n"
		. "					option.text = \"30\";\r\n"
		. "					option.setAttribute(\"value\", \"30\");\r\n"
		. "					days.add(option, null);\r\n"
		. "					break;\r\n"
		. "				case 30: //last was either april, june, september, november\r\n"
		. "					break;\r\n"
		. "				case 31: //last was either january, february, march, may, july, august, october, december\r\n"
		. "					days.remove(30);\r\n"
		. "					break;\r\n"
		. "			}\r\n"
		. "			break;\r\n"
		. "		case 1: //february\r\n"
		. "			switch (days.length) {\r\n"
		. "				case 29: //last was february\r\n"
		. "					break;\r\n"
		. "				case 30: //last was either april, june, september, november\r\n"
		. "					days.remove(29);\r\n"
		. "					break;\r\n"
		. "				case 31: //last was either january, february, march, may, july, august, october, december\r\n"
		. "					days.remove(30);\r\n"
		. "					days.remove(29);\r\n"
		. "					break;\r\n"
		. "			}\r\n"
		. "			break;\r\n"
		. "	}\r\n"
		. "}\r\n"
		. "\r\n"
		. "function windowLoaded() {\r\n"
		. "	window.onresize = function(event) {\r\n"
		. "		var elements;\r\n"
		. "		if (document.getElementsByClassName) {\r\n"
		. "			elements = document.getElementsByClassName(\"hintbox\");\r\n"
		. "		} else {\r\n"
		. "			var hasClassName = new RegExp(\"(?:^|\\s)\" + className + \"(?:$|\\s)\");\r\n"
		. "			var allElements = document.getElementsByTagName(\"*\");\r\n"
		. "			elements = [];\r\n"
		. "\r\n"
		. "			var element;\r\n"
		. "			for (var i = 0; (element = allElements[i]) != null; i++) {\r\n"
		. "				var elementClass = element.className;\r\n"
		. "				if (elementClass && elementClass.indexOf(className) != -1 && hasClassName.test(elementClass))\r\n"
		. "					elements.push(element);\r\n"
		. "			}\r\n"
		. "		}\r\n"
		. "		var element;\r\n"
		. "		for (var i = 0; i < elements.length; i++) {\r\n"
		. "			element = elements[i];\r\n"
		. "			if (element.style.visibility == \"visible\") {\r\n"
		. "				var elementName = element.getAttribute(\"id\");\r\n"
		. "				var obj = document.getElementById(elementName.substring(8, elementName.length));\r\n"
		. "				element.x = getPosOffset(obj, \"left\") + obj.offsetWidth;\r\n"
		. "				element.y = getPosOffset(obj, \"top\");\r\n"
		. "				element.style.left = element.x - clearBrowserEdge(element, obj, \"right\") + \"px\";\r\n"
		. "				element.style.top = element.y - clearBrowserEdge(element, obj, \"bottom\") + \"px\";\r\n"
		. "			}\r\n"
		. "		}\r\n"
		. "	};\r\n"
		. "	//instead of just cutting off the user when > 12 characters, give them an error/hint if js is enabled\r\n"
		. "	document.getElementById(\"unamefield\").setAttribute(\"maxlength\", null);\r\n"
		. "	document.getElementById(\"pwdfield\").setAttribute(\"maxlength\", null);\r\n"
		. "\r\n"
		. "	//in case the user's browser saved some of the form data for some reason,\r\n"
		. "	//make sure our state is synced up.\r\n"
		. "	var obj = document.getElementById(\"unamefield\");\r\n"
		. "	var length = obj.value.length;\r\n"
		. "	if (length >= 4 && length <= 12) {\r\n"
		. "		checkUsername(obj);\r\n"
		. "		usernameOk = true;\r\n"
		. "	}\r\n"
		. "	obj = document.getElementById(\"pwdfield\");\r\n"
		. "	length = obj.value.length;\r\n"
		. "	if (length >= 5 && length <= 12)\r\n"
		. "		passwordOk = true;\r\n"
		. "	updateSubmitButton();\r\n"
		. "}\r\n"
		. "\r\n"
		. "setStartupFunction(windowLoaded);\r\n"
		. "// ]]>\r\n"
		. "</script>\r\n"
		. "</head>\r\n"
		. "<body>\r\n"
		. "\r\n"
		. "<div id=\"stylized\" class=\"regform\">\r\n"
		. "<form action=\"index.php?action=regsubmit\" method=\"post\">\r\n"
		. "<h1>Project Throwback Registration</h1>\r\n"
		. "<p>Please be sure to read and act on any red prompt before hitting Submit.</p>\r\n"
		. "<div class=\"row\">\r\n"
		. "<div class=\"label\">Username<span class=\"small\">Your account's login ID</span></div>\r\n"
		. "<input type=\"text\" id=\"unamefield\" name=\"username\" maxlength=\"12\" onclick=\"showUsernameHint(this);\" onkeypress=\"changingUsername(this, event);\" onkeyup=\"usernameChanged(this, event);\" onpaste=\"event.returnValue = false;\" oncut=\"event.returnValue = false;\" />\r\n"
		. "</div>\r\n"
		. "\r\n"
		. "<div class=\"row\">\r\n"
		. "<div class=\"label\">Password</div>\r\n"
		. "<input type=\"password\" id=\"pwdfield\" name=\"password\" maxlength=\"12\" onclick=\"showPasswordHint(this);\" onkeypress=\"changingPassword(this, event);\" onkeyup=\"passwordChanged(this, event);\" onpaste=\"event.returnValue = false;\" oncut=\"event.returnValue = false;\" />\r\n"
		. "</div>\r\n"
		. "\r\n"
		. "<div class=\"row\">\r\n"
		. "<div class=\"label\">Birthday\r\n"
		. "<span class=\"small\">Only needed for character deletion</span>\r\n"
		. "</div>\r\n"
		. "<div class=\"birthdate\">\r\n"
		. "<select id=\"birthmonthselect\" name=\"birthmonth\" onchange=\"updateValidBirthdays(this);\">\r\n"
		. "<option value=\"1\">January</option>\r\n"
		. "<option value=\"2\">February</option>\r\n"
		. "<option value=\"3\">March</option>\r\n"
		. "<option value=\"4\">April</option>\r\n"
		. "<option value=\"5\">May</option>\r\n"
		. "<option value=\"6\">June</option>\r\n"
		. "<option value=\"7\">July</option>\r\n"
		. "<option value=\"8\">August</option>\r\n"
		. "<option value=\"9\">September</option>\r\n"
		. "<option value=\"10\">October</option>\r\n"
		. "<option value=\"11\">November</option>\r\n"
		. "<option value=\"12\">December</option>\r\n"
		. "</select>\r\n"
		. "<select id=\"birthdayselect\" name=\"birthday\">\r\n"
		. "<option value=\"1\">1</option>\r\n"
		. "<option value=\"2\">2</option>\r\n"
		. "<option value=\"3\">3</option>\r\n"
		. "<option value=\"4\">4</option>\r\n"
		. "<option value=\"5\">5</option>\r\n"
		. "<option value=\"6\">6</option>\r\n"
		. "<option value=\"7\">7</option>\r\n"
		. "<option value=\"8\">8</option>\r\n"
		. "<option value=\"9\">9</option>\r\n"
		. "<option value=\"10\">10</option>\r\n"
		. "<option value=\"11\">11</option>\r\n"
		. "<option value=\"12\">12</option>\r\n"
		. "<option value=\"13\">13</option>\r\n"
		. "<option value=\"14\">14</option>\r\n"
		. "<option value=\"15\">15</option>\r\n"
		. "<option value=\"16\">16</option>\r\n"
		. "<option value=\"17\">17</option>\r\n"
		. "<option value=\"18\">18</option>\r\n"
		. "<option value=\"19\">19</option>\r\n"
		. "<option value=\"20\">20</option>\r\n"
		. "<option value=\"21\">21</option>\r\n"
		. "<option value=\"22\">22</option>\r\n"
		. "<option value=\"23\">23</option>\r\n"
		. "<option value=\"24\">24</option>\r\n"
		. "<option value=\"25\">25</option>\r\n"
		. "<option value=\"26\">26</option>\r\n"
		. "<option value=\"27\">27</option>\r\n"
		. "<option value=\"28\">28</option>\r\n"
		. "<option value=\"29\">29</option>\r\n"
		. "<option value=\"30\">30</option>\r\n"
		. "<option value=\"31\">31</option>\r\n"
		. "</select>\r\n"
		. "<input type=\"text\" id=\"birthyearfield\" name=\"birthyear\" maxlength=\"4\" onkeyup=\"this.value = this.value.replace(/[^\d]/, '')\" />\r\n"
		. "</div>\r\n"
		. "</div>\r\n"
		. "<div><input id=\"register\" type=\"submit\" value=\"Register\" /></div>\r\n"
		. "<div class=\"spacer\"></div>\r\n"
		. "</form>\r\n"
		. "</div>\r\n"
		. "\r\n"
		. "</body>\r\n"
		. "</html>";
}

function doRegister() {
	if (!isset($_POST["username"]) || !isset($_POST["password"]))
		require('hackingattempt.php');

	//client side JS should've checked these, but just in case there was a glitch, or js is disabled...
	if (!is_numeric($_POST["birthyear"])) {
		echo 'Birthyear must be a number!';
	} else if (strlen($_POST["password"]) < 5) {
		echo 'Password is too short. Your password must be at between 5-12 characters long. Please try another.<br \><input type="button" value="Back" onclick="history.back(-1)" />';
	} else if (strlen($_POST["password"]) > 12) {
		echo 'Password is too long. Your password must be at between 5-12 characters long. Please try another.<br \><input type="button" value="Back" onclick="history.back(-1)" />';
	} else if (strlen($_POST["username"]) < 4) {
		echo 'Username is too short. Your username must be between 4-12 characters long. Please try another.<br \><input type="button" value="Back" onclick="history.back(-1)" />';
	} else if (strlen($_POST["username"]) > 12) {
		echo 'Username is too long. Your username must be between 4-12 characters long. Please try another.<br \><input type="button" value="Back" onclick="history.back(-1)" />';
	} else if (!preg_match('/^[A-Za-z0-9_]+$/', $_POST["username"])) {
		//Surprisingly enough, the client does not give "You have entered an incorrect LOGIN ID" for any
		//names with at least one non-alphanumeric character (and underscore), except for period and at sign.
		//But, let's just limit them to alphanumeric and underscore anyway.
		echo 'Username must only consist of the characters a-z (lowercase letters), A-Z (uppercase letters), 0-9 (numbers), and _ (underscore). Please try another.<br \><input type="button" value="Back" onclick="history.back(-1)" />';
	} else {
		require_once('databasemanager.php');
		$con = makeDatabaseConnection();

		$alreadyexists = false;
		$ps = $con->prepare("SELECT COUNT(*) FROM `accounts` WHERE `name` = ?");
		$ps->bind_param('s', $_POST["username"]);
		$ps->execute();
		$ps->bind_result($usermatchcount);
		if ($ps->fetch() && $usermatchcount > 0)
			$alreadyexists = true;
		$ps->close();

		if ($alreadyexists) {
			echo 'That username is already being used. Please try another.<br \><input type="button" value="Back" onclick="history.back(-1)" />';
		} else {
			require_once('hashfunctions.php');
			$salt = makeSalt();
			$passhash = makeSaltedSha512Hash($_POST["password"], $salt);

			$birthday = $_POST["birthyear"] * 10000 + intval($_POST["birthmonth"]) * 100 + intval($_POST["birthday"]);

			$ps = $con->prepare("INSERT INTO `accounts`(`name`,`password`,`salt`,`birthday`) VALUES (?,?,?,?)");
			$ps->bind_param('sssi', $_POST["username"], $passhash, $salt, $birthday);
			$ps->execute();
			$ps->close();
			echo 'User '.$_POST["username"].' registered successfully.';
		}
		$con->close();
	}
}